server.port=8080
------

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://174.129.112.201:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=paciente-service
spring.cloud.gateway.routes[1].uri=http://54.152.26.25:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/pacientes/**

spring.cloud.gateway.routes[2].id=medical-service
spring.cloud.gateway.routes[2].uri=http://100.31.131.105:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/medical/**,/rabbit/**,/controles/**,/evoluciones/**,/examenes/**,/fichas/**,/indicaciones/**,/medicamentos/**,/signos-vitales/**

spring.cloud.gateway.routes[3].id=bff-service
spring.cloud.gateway.routes[3].uri=http://34.203.222.130:8090
spring.cloud.gateway.routes[3].predicates[0]=Path=/bff/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

jwt.secret=${JWT_SECRET:miClaveSecretaMuyLargaYSeguraParaJWT1234567890ABCDEF}

logging.level.org.springframework.security=INFO
logging.level.com.cuidadoseguro=DEBUG
