server.port=8080
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /api/auth/${segment}

spring.cloud.gateway.routes[1].id=paciente-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/pacientes/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

spring.cloud.gateway.routes[2].id=medical-service
spring.cloud.gateway.routes[2].uri=http://medical-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/medical/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

jwt.secret=miClaveSecretaMuyLargaYSeguraParaJWT1234567890ABCDEF
